# Generated by Django 5.2.7 on 2025-10-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('precio', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('detalles', models.TextField()),
                ('imagen', models.CharField(max_length=300)),
            ],
        ),
    ]
